apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydjango-web-deployment-thanksgiving
spec:
  selector:
    matchLabels:
      app: mydjango-web-thanksgiving
  replicas: 2
  template:
    metadata:
      labels:
        app: mydjango-web-thanksgiving
    spec:
      containers:
        - name: mydjango-web-thanksgiving
          image: 0857/mydjango_web:thanksgiving
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mydjango-web-svc-thanksgiving
spec:
  selector:
    app: mydjango-web-thanksgiving
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
#use port-forwarding nodePort(30000-32767):8000

