apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydjango-web-deployment
spec:
  selector:
    matchLabels:
      app: mydjango-web
  replicas: 2
  template:
    metadata:
      labels:
        app: mydjango-web
    spec:
      containers:
      - name: mydjango-web
        image: 0857/mydjango_web:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mydjango-web-svc
spec:
  selector:
    app: mydjango-web
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
 
#use port-forwarding nodePort(30000-32767):8000
    
  